---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tools.robot.dev
  resources:
  - vscodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.robot.dev
  resources:
  - vscodes/finalizers
  verbs:
  - update
- apiGroups:
  - tools.robot.dev
  resources:
  - vscodes/status
  verbs:
  - get
  - patch
  - update
