# permissions for end users to view vscodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vscode-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: vscode-viewer-role
rules:
- apiGroups:
  - tools.robot.dev
  resources:
  - vscodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.robot.dev
  resources:
  - vscodes/status
  verbs:
  - get
