FROM jjoneson/workforce-builder-ui:latest AS builder

WORKDIR /app

COPY ./workforce-core /app/workforce-core
RUN yarn workspace workforce-core run build

COPY ./workforce-api-client /app/workforce-api-client
RUN yarn workspace workforce-api-client run build

COPY ./workforce-ui-core /app/workforce-ui-core
RUN yarn workspace workforce-ui-core run build

ENV PUBLIC_URL=/workforce-ui

COPY ./workforce-ui /app/workforce-ui/
RUN yarn workspace workforce-ui run build

FROM nginxinc/nginx-unprivileged:1.25-alpine
COPY --from=builder /app/workforce-ui/build /usr/share/nginx/html
COPY ./workforce-ui/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]